# ============================
#  docker-compose.yml (Next + Prisma + SQLite)
# ============================

version: "3.9"

services:
  web:
    container_name: nextjs_app
    build:
      context: .
      dockerfile: Dockerfile
    # Puedes cambiar este argumento si quieres que use el modo dev
    environment:
      NODE_ENV: production
      DATABASE_URL: "file:./prisma/dev.db"
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      # Permite que el archivo de base de datos SQLite sea persistente
      - ./prisma/dev.db:/app/prisma/dev.db
      # (opcional) Si quieres mantener sincronizado el código para desarrollo:
      # - .:/app
    command: >
      sh -c "npx prisma migrate deploy &&
             npm start"
    depends_on:
      - migrations

  migrations:
    container_name: prisma_migrations
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "file:./prisma/dev.db"
    command: >
      sh -c "npm install &&
             npx prisma generate &&
             npx prisma migrate deploy &&
             npx tsx prisma/seed.ts"
    restart: "on-failure"

volumes:
  prisma_data:
    driver: local
